minimumReleaseAgeExclude:
  - '@trycua/cua-driver-darwin-arm64@0.31.0'
  - '@trycua/cua-driver-darwin-x64@0.31.0'
  - '@trycua/cua-driver-linux-arm64-gnu@0.31.0'
  - '@trycua/cua-driver-linux-x64-gnu@0.31.0'
  - '@trycua/cua-driver-win32-arm64-msvc@0.31.0'
  - '@trycua/cua-driver-win32-x64-msvc@0.31.0'
  - '@trycua/cua-driver@0.31.0'
